### ISSUE TITLE
sqlacodegen connection string

### ISSUE THREAD

**Issue by ryancartoon** [sqlanywhere/sqlalchemy-sqlany#11]
Hi,

I'm trying to generate a model file by sqlacodegen with following format. but it reports 'database server not found, -100'.

`sqlacodegen sqlalchemy_sqlany://user:password@ip/dbname --outfile model.py`

I can connect to the db by sqlanydb with odbc.ini .

Please kindly let me know how to do this. 

Thanks.

**Comment by gperrow-SAP** [comment]
Please post the command you used to start the database server. If you started it using dbeng17 (rather than dbsrv17), make sure you add the "-x tcpip" switch.

**Comment by ryancartoon** [comment]
Thanks for the repsonse. I have solved the problem by giving the right port number. Please close the issue.

`sqlacodegen sqlalchemy_sqlany://user:password@ip:port/dbname --outfile model.py`
