### ISSUE TITLE
typemap parameter has been deprecated in sqlalchemy

### ISSUE THREAD

**Issue by hynek** [sqlanywhere/sqlalchemy-sqlany#13]
As of sqlalchemy 1.3, using sqlalchemy-sqlany raises a warning:

```
<string>:2: SADeprecationWarning: The text.typemap parameter is deprecated and will be removed in a future release.  Please refer to the TextClause.columns() method.
```

I've tracked it back to this line:

https://github.com/sqlanywhere/sqlalchemy-sqlany/blob/f7b6622d8909ee67d41fc5c4c780f262c2b2f58a/sqlalchemy_sqlany/base.py#L466

**Comment by hynek** [comment]
For the record, SQLAlchemy 1.4 has been released on 2021-03-15 and is **not compatible with sqlalchemy-sqlany** anymore:

```
self = <sqlalchemy_sqlany.base.SQLAnyDialect object at 0x1076761c0>, connection = <sqlalchemy.engine.base.Connection object at 0x107732d90>

    def _get_default_schema_name(self, connection):
        return connection.scalar(
>                    text("SELECT current user",
                     typemap={'user_name': Unicode})
             )
E       TypeError: text() got an unexpected keyword argument 'typemap'

.direnv/python-3.9.2/lib/python3.9/site-packages/sqlalchemy_sqlany/base.py:465: TypeError
```

**Comment by dekay2001** [comment]
> For the record, SQLAlchemy 1.4 has been released on 2021-03-15 and is **not compatible with sqlalchemy-sqlany** anymore:
> 
> ```
> self = <sqlalchemy_sqlany.base.SQLAnyDialect object at 0x1076761c0>, connection = <sqlalchemy.engine.base.Connection object at 0x107732d90>
> 
>     def _get_default_schema_name(self, connection):
>         return connection.scalar(
> >                    text("SELECT current user",
>                      typemap={'user_name': Unicode})
>              )
> E       TypeError: text() got an unexpected keyword argument 'typemap'
> 
> .direnv/python-3.9.2/lib/python3.9/site-packages/sqlalchemy_sqlany/base.py:465: TypeError
> ```

Bumping this.  We just ran into this at my organization and its potentially a big problem for us that may force us to evaluate use of ASA in the long term.  We have a lot of customers who rely on this integration working.  Would like to see continued support of this library.  Are there plans to fix this?

**Comment by DanCummins-SAP** [comment]
Hi Hynek and dekay2001,

Just to let you know we saw your messages and we are working on a fix.

Kind regards,
Dan

**Comment by DanCummins-SAP** [comment]
May I close this issue?
Kind regards,
Dan

**Comment by ASk1** [comment]
@DanCummins-SAP - please approve PR #15

**Comment by DanCummins-SAP** [comment]
I just posted this:
https://pypi.org/project/sqlalchemy-sqlany/1.0.4/

Can you let me know your feedback?
Thanks,
Dan

**Comment by hynek** [comment]
It works for me.
